### ISSUE TITLE
decimal precision on extension

### ISSUE THREAD

**Issue by enerestar** [hashgraph/hedera-browser-extension#3]
In the Chrome Browser Extension, when you manually input the maximum value that you are willing to allow the website to charge your wallet, it allows you to input the full precision of $0.000672, but then responds with only two decimal precision in the hbar equivalent.

However, if you click anywhere else on the page and then click the Hedera Chrome Browser Extension icon (to reopen it) you can see full precision of the hbar equivalent (0.00560000 ℏ).

This is a UI display issue in the extension app and could result in people thinking that they can't specify full precision (smaller, safer values) when allowing a web site to charge the wallet.

**Comment by calvinchengx** [comment]
Resolved via https://github.com/hashgraph/hedera-browser-extension/commit/e479d8dbf824045acf73e8c35136b6fb2dd73a08
